/* eslint-disable import/prefer-default-export */
import axios from '../assets/img/skills/axios.png';
import bootstrap from '../assets/img/skills/bootstrap.png';
import css from '../assets/img/skills/css.jpg';
import emailjs from '../assets/img/skills/emailjs.png';
import html from '../assets/img/skills/html.jpg';
import javascript from '../assets/img/skills/javascript.png';
import jwt from '../assets/img/skills/jwt.jpeg';
import mysql from '../assets/img/skills/mysql.png';
import php from '../assets/img/skills/php.png';
import reactRouterDom from '../assets/img/skills/react-router-dom.png';
import react from '../assets/img/skills/react.png';
import redux from '../assets/img/skills/redux.jpg';
import anglais from '../assets/img/skills/anglais.jpg';
import management from '../assets/img/skills/management.jpg';
import polyvalence from '../assets/img/skills/polyvalence.jpg';
import redaction from '../assets/img/skills/redaction.jpg';
import rigueur from '../assets/img/skills/rigueur.jpg';
import autonomie from '../assets/img/skills/autonomie.jpg';
import seo from '../assets/img/skills/seo.jpg';
import sociabilité from '../assets/img/skills/sociabilité.jpg';
import team from '../assets/img/skills/team.jpg';

const skills = [
  {
    name: 'HTML5',
    champs: '',
    level: '5',
    experience: '10 mois',
    category: 'HTML',
    picture: html,
    color: 'blue',
    text: 'white',
    id: '1',
  },
  {
    name: 'CSS3',
    champs: '',
    level: '4',
    experience: '10 mois',
    category: 'CSS',
    picture: css,
    color: 'blue',
    text: 'white',
    id: '2',
  },
  {
    name: 'Javascript',
    champs: '',
    level: '4',
    experience: '2 mois',
    category: 'Front-end',
    picture: javascript,
    color: 'blue',
    text: 'white',
    id: '3',
  },
  {
    name: 'ReactJS',
    champs: '',
    level: '5',
    experience: '5 mois',
    category: 'Front-end',
    picture: react,
    color: 'blue',
    text: 'white',
    id: '4',
  },
  {
    name: 'Bootstrap',
    champs: '',
    level: '5',
    experience: '7 mois',
    category: 'CSS',
    picture: bootstrap,
    color: 'blue',
    text: 'white',
    id: '5',
  },
  {
    name: 'Axios',
    champs: '',
    level: '4',
    experience: '5 mois',
    category: 'Front-end',
    picture: axios,
    color: 'blue',
    text: 'white',
    id: '6',
  },
  {
    name: 'Redux',
    champs: '',
    level: '5',
    experience: '5 mois',
    category: 'Front-end',
    picture: redux,
    color: 'blue',
    text: 'white',
    id: '7',
  },
  {
    name: 'React-jwt',
    champs: '',
    level: '3',
    experience: '2 mois',
    category: 'Front-end',
    picture: jwt,
    color: 'blue',
    text: 'white',
    id: '8',
  },
  {
    name: 'React-Router-Dom',
    champs: '',
    level: '5',
    experience: '5 mois',
    category: 'Front-end',
    picture: reactRouterDom,
    color: 'blue',
    text: 'white',
    id: '9',
  },
  {
    name: 'emailJS',
    champs: '',
    level: '5',
    experience: '5 mois',
    category: 'Front-end',
    picture: emailjs,
    color: 'blue',
    text: 'white',
    id: '10',
  },
  {
    name: 'Management',
    champs: 'management, humain, encadrement, direction',
    level: '5',
    experience: '5 ans',
    category: 'Management',
    picture: management,
    color: 'brown',
    text: 'blue',
    id: '12',
  },
  {
    name: 'Travail en équipe',
    champs: '',
    level: '5',
    experience: '8 ans',
    category: 'Soft skills',
    picture: team,
    color: 'brown',
    text: 'blue',
    id: '13',
  },
  {
    name: 'Sociabilité',
    champs: '',
    level: '5',
    experience: '/',
    category: 'Soft skills',
    picture: sociabilité,
    color: 'brown',
    text: 'blue',
    id: '14',
  },
  {
    name: 'Rigueur',
    champs: '',
    level: '5',
    experience: '/',
    category: 'Soft skills',
    picture: rigueur,
    color: 'brown',
    text: 'blue',
    id: '15',
  },
  {
    name: 'Autonomie',
    champs: '',
    level: '4',
    experience: '/',
    category: 'Soft skills',
    picture: autonomie,
    color: 'brown',
    text: 'blue',
    id: '16',
  },
  {
    name: 'Polyvalence',
    champs: 't',
    level: '4',
    experience: '/',
    category: 'Soft skills',
    picture: polyvalence,
    color: 'brown',
    text: 'blue',
    id: '17',
  },
  {
    name: 'Rédaction',
    champs: '',
    level: '5',
    experience: '8 ans',
    category: 'Langues',
    picture: redaction,
    color: 'brown',
    text: 'blue',
    id: '18',
  },
  {
    name: 'SEO',
    champs: '',
    level: '4',
    experience: '8 ans',
    category: 'SEO',
    picture: seo,
    color: 'brown',
    text: 'blue',
    id: '19',
  },
  {
    name: 'Anglais',
    champs: '',
    level: '3',
    experience: 'C1',
    category: 'Langues',
    picture: anglais,
    color: 'brown',
    text: 'blue',
    id: '20',
  },
  {
    name: 'PHP',
    champs: '',
    level: '3',
    experience: '4 mois',
    category: 'Back-end',
    picture: php,
    color: 'blue',
    text: 'white',
    id: '21',
  },
  {
    name: 'MySql',
    champs: '',
    level: '3',
    experience: '4 mois',
    category: 'Back-end',
    picture: mysql,
    color: 'blue',
    text: 'white',
    id: '11',
  },
];

export { skills };
